[package]
name = "crate-spec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.7.6"
cms = "0.2.2"
bincode = "2.0.0-rc.3"